// Standalone PDF renderer, run as a child process so @react-pdf/renderer
// loads in a clean Node ESM context (its async yoga-layout WASM init breaks
// when bundled by Next/webpack). Reads JSON payload from argv[2] (a temp file)
// and writes the PDF bytes to argv[3].
import fs from "fs";
import React from "react";
import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
  renderToBuffer,
} from "@react-pdf/renderer";

const COLORS = { ink: "#102A3D", paper: "#F7F3EA", teal: "#2F7A6F", slate: "#8C97A1" };

function statusColor(status) {
  if (status === "critical") return "#D14B3D";
  if (status === "borderline") return "#D69A2D";
  return "#2F7A6F";
}

const styles = StyleSheet.create({
  page: { padding: 40, fontSize: 10, color: COLORS.ink, fontFamily: "Helvetica", backgroundColor: "#FFFFFF" },
  header: { borderBottomWidth: 2, borderBottomColor: COLORS.teal, paddingBottom: 12, marginBottom: 16 },
  wordmark: { fontSize: 18, fontFamily: "Helvetica-Bold", color: COLORS.teal },
  doctorLine: { marginTop: 4, fontSize: 11, color: COLORS.ink },
  spec: { color: COLORS.slate, fontSize: 9 },
  patientBlock: { marginBottom: 16 },
  patientName: { fontSize: 14, fontFamily: "Helvetica-Bold" },
  meta: { color: COLORS.slate, marginTop: 2 },
  sectionTitle: { fontSize: 12, fontFamily: "Helvetica-Bold", marginTop: 14, marginBottom: 6 },
  table: { borderWidth: 1, borderColor: "#E2DCCD" },
  row: { flexDirection: "row", borderBottomWidth: 1, borderBottomColor: "#E2DCCD" },
  rowHeader: { backgroundColor: COLORS.paper },
  cell: { padding: 6, fontSize: 9 },
  cMetric: { width: "32%" },
  cValue: { width: "18%", fontFamily: "Helvetica-Bold" },
  cRange: { width: "30%", color: COLORS.slate },
  cStatus: { width: "20%", fontFamily: "Helvetica-Bold" },
  note: { marginBottom: 6, paddingBottom: 6, borderBottomWidth: 1, borderBottomColor: "#EFE9DA" },
  noteTime: { color: COLORS.slate, fontSize: 8, marginBottom: 2 },
  empty: { color: COLORS.slate, fontStyle: "italic" },
  footer: { position: "absolute", bottom: 28, left: 40, right: 40, fontSize: 8, color: COLORS.slate, textAlign: "center", borderTopWidth: 1, borderTopColor: "#E2DCCD", paddingTop: 8 },
});

const h = React.createElement;

function ReportDoc(data) {
  return h(Document, null,
    h(Page, { size: "A4", style: styles.page },
      h(View, { style: styles.header },
        h(Text, { style: styles.wordmark }, "ContextCare AI"),
        h(Text, { style: styles.doctorLine }, `Dr. ${data.doctorName}`),
        data.specialization ? h(Text, { style: styles.spec }, data.specialization) : null
      ),
      h(View, { style: styles.patientBlock },
        h(Text, { style: styles.patientName }, data.patientName),
        h(Text, { style: styles.meta }, `Report date: ${data.reportDate}`)
      ),
      h(Text, { style: styles.sectionTitle }, "Diagnostic Metrics"),
      h(View, { style: styles.table },
        h(View, { style: [styles.row, styles.rowHeader] },
          h(Text, { style: [styles.cell, styles.cMetric] }, "Metric"),
          h(Text, { style: [styles.cell, styles.cValue] }, "Value"),
          h(Text, { style: [styles.cell, styles.cRange] }, "Reference range"),
          h(Text, { style: [styles.cell, styles.cStatus] }, "Status")
        ),
        ...data.metrics.map((m, i) =>
          h(View, { style: styles.row, key: i },
            h(Text, { style: [styles.cell, styles.cMetric] }, m.label),
            h(Text, { style: [styles.cell, styles.cValue] }, `${m.value} ${m.unit}`),
            h(Text, { style: [styles.cell, styles.cRange] }, `${m.refMin}-${m.refMax} ${m.unit}`),
            h(Text, { style: [styles.cell, styles.cStatus, { color: statusColor(m.status) }] }, m.status.toUpperCase())
          )
        )
      ),
      h(Text, { style: styles.sectionTitle }, "Clinical Notes"),
      data.notes.length === 0
        ? h(Text, { style: styles.empty }, "No notes recorded for this patient.")
        : data.notes.map((n, i) =>
            h(View, { style: styles.note, key: i },
              h(Text, { style: styles.noteTime }, n.createdAt),
              h(Text, null, n.content)
            )
          ),
      h(Text, { style: styles.footer, fixed: true },
        "Generated by ContextCare AI - for clinical reference only, not a diagnostic document."
      )
    )
  );
}

async function main() {
  const inPath = process.argv[2];
  const outPath = process.argv[3];
  const data = JSON.parse(fs.readFileSync(inPath, "utf8"));
  const buffer = await renderToBuffer(ReportDoc(data));
  fs.writeFileSync(outPath, buffer);
}

main().then(() => process.exit(0)).catch((e) => {
  console.error(e);
  process.exit(1);
});
